#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["src/services/MyPoints.Account/MyPoints.Account.csproj", "src/services/MyPoints.Account/"]
RUN dotnet restore "src/services/MyPoints.Account/MyPoints.Account.csproj"
COPY . .
WORKDIR "/src/src/services/MyPoints.Account"
RUN dotnet build "MyPoints.Account.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MyPoints.Account.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MyPoints.Account.dll"]