name: MyPoints.Catalog CI

on:
  push:
    branches: [ master ]
    paths: 
      - src/services/MyPoints.Catalog
      - src/libs
      - src/tests/MyPoints.Catalog.Test]
  pull_request:
    branches: [ master ]
    paths: [src/services/MyPoints.Catalog, src/libs, src/tests/MyPoints.Catalog.Test]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file src/services/MyPoints.Catalog/Dockerfile --tag mypoints-catalog:$(date +%s)
