name: MyPoints.Identity

on:
  push:
    branches: [ master ]
#     paths: 
#       - src/services/MyPoints.Identity
#       - src/libs
#       - src/tests/MyPoints.Identity.Test

  pull_request:
    branches: [ master ]
#     paths:
#       - src/services/MyPoints.Identity
#       - src/libs
#       - src/tests/MyPoints.Identity.Test
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.102"

      - name: Build with dotnet
        run: dotnet build src/services/MyPoints.Identity/MyPoints.Identity.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish src/services/MyPoints.Identity/MyPoints.Identity.csproj -c Release -o dev/myapp

